### ISSUE TITLE
Mac bundle pops up messages about missing hash functions

### ISSUE THREAD

**Issue by njbooher** [ResearchIT/IGV-ScanFold#10]
It still works. Find a way to silence the warnings from Python.

**Comment by rjandr** [comment]
Tested on system without homebrew to see if that was issue, but the same error popped up.

**Comment by njbooher** [comment]
https://github.com/igvteam/igv/blob/master/src/main/java/org/broad/igv/util/RuntimeUtils.java#L89

IGV apparently is just looking for the word 'error' in output. Will probably update run_scanfold.py to filter out hash function messages.

**Comment by njbooher** [comment]
https://github.com/ResearchIT/scanfoldigv/commit/2366c794af9ea32569b788bda20f2817b8a64a50
pretty sure this takes care of it
