### ISSUE TITLE
Windows bundle not running ScanFold

### ISSUE THREAD

**Issue by wbrouse** [ResearchIT/IGV-ScanFold#12]
When trying to run ScanFold on both the entire visible region and a targeted region the log output window says done immediately after clicking run. No data is generated but it says that is completed. The screenshot below displays this issue. The release being used is 1.0.7. 
![IGVWindowsProblem](https://user-images.githubusercontent.com/60672421/110185001-e0a03080-7dd6-11eb-9570-3ee7239910fb.png)

**Comment by njbooher** [comment]
What version of Windows?

https://support.microsoft.com/en-us/windows/see-which-version-of-windows-10-you-have-12d35019-4da9-0cb1-ba47-f8b031b712ad

Also does it say '64-bit operating system' or '32-bit operating system' ?

**Comment by wbrouse** [comment]
Both were Windows 10 and 64-bit operating systems.

**Comment by njbooher** [comment]
Can you attach igv.log from your User folder.,

e.g.

C:\Users\Nick\igv\igv.log

**Comment by wbrouse** [comment]
I think I figured out the issue. We were following the readme, which said
to use the IGV.bat or IGV-launcher.bat instead of the runme.bat. When I use
the runme.bat everything works.

**Comment by rjandr** [comment]
We may need to put a readme in the top folder to explain that we just need to use the runme.bat (or make an enhancement).
There are other readmes (like in the IGV folder) that could complicate things.
