### ISSUE TITLE
PI Suggestions

### ISSUE THREAD

**Issue by wbrouse** [ResearchIT/IGV-ScanFold#13]
On Mac with 1.0.7, I still get the ERROR:root:code message when trying to run ScanFold, but it still runs and gives me outputs. The other error that occurs is a null error for Varna if I uncheck the global refold, but that is always sent at the end of the run just stating that the file is empty. When I was talking to Walter he was hoping we could get rid of these error messages to avoid any reviewer and user complaints.

Walter also would like us to remove the "gui" part of the text in the "Run ScanFoldgui" tab and simply have it displayed as Run ScanFold.

**Comment by rjandr** [comment]
Run ScanFoldgui has been changed to Run ScanFold. Other problems are still pending a fix, and will remain open as separate issues
