### ISSUE TITLE
Add predicted runtime or progress bar to Scanfold window

### ISSUE THREAD

**Issue by njbooher** [ResearchIT/IGV-ScanFold#19]

**Comment by rjandr** [comment]
We can add an estimated runtime based on the number of windows. Right now I'm calculating roughly 2 windows per second.
So we can just print that simple estimation for now (not sure if that completely closes the issue).

`print(f'Estimated runtime = {round((number_windows*2)/60), 2)} minutes')`

**Comment by rjandr** [comment]
Just added a simple runtime estimation for now.
