### ISSUE TITLE
Create a single IGV-ScanFold .exe file for running on windows

### ISSUE THREAD

**Issue by rjandr** [ResearchIT/IGV-ScanFold#20]
We should have parity between the windows and mac version, where each is simply run from a single icon.

https://superuser.com/questions/868340/how-can-i-convert-a-windows-batch-script-to-a-exe

**Comment by njbooher** [comment]
Mac apps are actually folders in disguise. 

That method you linked makes a self-extracting zip. If we bundled everything in it, you'd just be adding however long it takes to extract the zips you download from GitHub to the startup time every time you run it.

We could maybe turn the existing bat file into a exe if you think it'd be friendlier, but it would still need to sit next to a bunch of folders to avoid that increased startup time.

We could also just rename run_me.bat to IGV-Scanfold.bat if that would help.

**Comment by njbooher** [comment]
I guess it's possible to disable the compression

https://stackoverflow.com/questions/18213660/iexpress-disable-compression

i'll fiddle with it.

**Comment by rjandr** [comment]
> We could also just rename run_me.bat to IGV-Scanfold.bat if that would help.

This is a decent option too. Haven't had any specific requests for the .exe file, but have noticed some users aren't sure what to do with the run_me.bat ; just disguising the .bat file as the app is a great option if the "clickable icon" approach doesn't work.

**Comment by njbooher** [comment]
I renamed the bat file
