### ISSUE TITLE
Version 0.1.9 Windows Testing Issues

### ISSUE THREAD

**Issue by wbrouse** [ResearchIT/IGV-ScanFold#27]
When RNAfold is used with the reverse strand for the entire visible region and selected regions the extracted structures track is incorrect (i.e. it output the correct data to the track but the bars do not align with the arc diagram/bp track, they seem to be flipped as if it is forward strand). The first screenshot below shows what I mean (bottom track). When RNAstructure is used on the entire visible region or a selected region for forward and reverse strand no extracted structures track is made and the ED track that is generated is empty (top 4 tracks of second screenshot). 

![Mac:Windows_RNAfold_Rev](https://user-images.githubusercontent.com/60672421/118705119-75fb7000-b7dd-11eb-99c9-faa7f1c74695.png)

I also noticed that the text box at the top of the scanfoldgui pop up window telling users whether they will be scanning the selected region or the entire visible region can be edited by the user. 

One additional thing I noticed is that the scanfoldgui pop up window has some weird things happening. The LogOutput box covers the LogOutput label, and both the Run and Close tabs are very difficult to see and select. I tried adjusting its size but nothing helped so I actually had to get rid of my taskbar to be able to start ScanFold runs. The second screenshot demonstrates what I mean.

![Window_scanfoldgui_popup](https://user-images.githubusercontent.com/60672421/118705133-785dca00-b7dd-11eb-9d51-4b15c07be9d9.png)

**Comment by njbooher** [comment]
I think the editable message box and GUI window size issues should be fixed.

Does #28 cover the other issues?
