### ISSUE TITLE
Release 0.1.7 strand error 

### ISSUE THREAD

**Issue by rjandr** [ResearchIT/IGV-ScanFold#3]
Right now there is a line in ScanFold-Scan_IGV.py that overrides the strand settings.    

line 270 print("Remove LINES about REVERSE STRAND")
line 271     strand = "reverse"

We need to remove this.

**Comment by njbooher** [comment]
Can you confirm that this is fixed with the latest commit on master?

**Comment by rjandr** [comment]
Ran a dozen tests, looks good.
