### ISSUE TITLE
Mac Action #60

### ISSUE THREAD

**Issue by wbrouse** [ResearchIT/IGV-ScanFold#31]
When installing the program, we are back to 2 zipped files before the icon appears, I don't have a problem with it or know if it can be changed but I am assuming some reviewers may have an issue with that. 

For ScanFold RNAfold the reverse strand extracted structures still appear to be flipped for visible and selected scans.

For ScanFold RNAstructure no extracted structure tracks are generated for visible or selected scans on forward or reverse strand scans. If we can make a track for it that would be great, but if not then that is fine as well.

**Comment by njbooher** [comment]
#26 
![118704846-274dd600-b7dd-11eb-8566-d2215e800c16](https://user-images.githubusercontent.com/533823/122474449-d91d2580-cf88-11eb-97b0-7d0145f04c6e.png)

**Comment by njbooher** [comment]
The double zip is fixed. I think the other issues are covered by #28 and #34
