### ISSUE TITLE
Windows Action #52

### ISSUE THREAD

**Issue by wbrouse** [ResearchIT/IGV-ScanFold#32]
When installing the program, we are back to 2 zipped files before the batch script appears, which is not a problem to me but I could see a reviewer having issues with that. If it can be changed to one zipped file that would be great, but if not that is fine too.

When trying to run ScanFold the "Run" button in the parameters window is not visible to click even when the computer's task bar is removed, but you can just hit enter to start the scan. The resolution of the testing computer is 1366x768, which is the max setting for the machine.

For ScanFold RNAfold the reverse strand extracted structures still appear to be flipped for visible and selected scans.

For ScanFold RNAstructure no extracted structure tracks are generated for visible or selected scans on forward or reverse strand scans. If we can make a track for it that would be great, but if not then that is fine as well.

**Comment by njbooher** [comment]
#27 
![118704846-274dd600-b7dd-11eb-8566-d2215e800c16](https://user-images.githubusercontent.com/533823/122474625-1b466700-cf89-11eb-90c5-aede9b01984a.png)

**Comment by njbooher** [comment]
The double zip is fixed. And the run window is now shorter and should fully appear on smaller monitors.

I think the other issues are covered by #28 and #34
